# Generated by Django 4.2.10 on 2024-02-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_company', models.CharField(max_length=100)),
                ('customer_notes', models.TextField(null=True)),
                ('arrived_date', models.DateField()),
                ('deal_won', models.BooleanField(default=False)),
                ('deal_assigned', models.BooleanField(default=False)),
                ('custRegiteredByUser', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Customer',
                'ordering': ['-arrived_date'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(max_length=100)),
                ('deal_status', models.CharField(choices=[('Lost', 'Lost'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=30)),
                ('deal_initiationDate', models.DateField()),
                ('deal_expectedCloseDate', models.DateField()),
                ('deal_amount', models.IntegerField()),
                ('dealCreatedByUser', models.CharField(default='', max_length=100)),
                ('deal_withCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmManagerApp.customer')),
            ],
            options={
                'db_table': 'Deal',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('Open', 'Open'), ('Wait', 'Wait'), ('Closed', 'Closed')], max_length=30)),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.TextField(null=True)),
                ('task_dueDate', models.DateField()),
                ('taskCreatedByUser', models.CharField(default='', max_length=100)),
                ('task_relatedToDeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmManagerApp.deal')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interacted_mode', models.CharField(choices=[('Email', 'Email'), ('Call', 'Call'), ('Meeting', 'Meeting')], max_length=30)),
                ('interacted_time', models.DateTimeField()),
                ('interaction_notes', models.TextField(null=True)),
                ('intrAddedByUser', models.CharField(default='', max_length=100)),
                ('interacted_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmManagerApp.customer')),
            ],
            options={
                'db_table': 'Interaction',
            },
        ),
    ]
